export const AccountTypes = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
  USER_SIGNUP: 'USER_SIGNUP',
};

export const Types = {
  MAP_COOKIE_TO_STATE: 'MAP_COOKIE_TO_STATE',
  MAP_COOKIE_TO_STATE_SUCCESS: 'MAP_COOKIE_TO_STATE_SUCCESS',
};
