const callbackHandlerEnums = {
  CHANGE_INPUT: 'CHANGE_INPUT',
  FETCH_RELATIONSHIPS: 'FETCH_RELATIONSHIPS',
  NEXT_SLIDESHOW: 'NEXT_SLIDESHOW',
  PREVIOUS_SLIDESHOW: 'PREVIOUS_SLIDESHOW',
};

export default callbackHandlerEnums;
